app/diseases/urls.py
from importlib.resources import path
from django.urls import path, re_path, include, reverse_lazy
from . import views
from diseases import views as diseases_views
from django.conf import settings
from django.conf.urls.static import static
from .models import DiseaseF, Element, Composition, Fruit_Element, Fruit
from django.template import loader

urlpatterns = [
    path('', diseases_views.fruit_therapy),
    path('dis_element/', views.dis_element, name="dis_element"),
    path('diseases_list/', diseases_views.diseases_list), 
    path('element_list/', diseases_views.element_list), 
    path('fruit_therapy/', diseases_views.fruit_therapy, name='fruit_therapy'),
    path('elements/', diseases_views.index_elements, name='element'),
    path('elements/<int:element_id>/', diseases_views.detail_element, name='detail_element'),
    path('compositions/', diseases_views.index_composition, name = 'composition'),
    path('compositions/<int:composition_id>/', diseases_views.detail, name='detail'),
    path('fruit/', diseases_views.index_fruit, name='fruit'),
    path('fruit/<int:pk>/', diseases_views.detail_fruit, name='detail_fruit'),
    
    path('disease/', diseases_views.index_disease, name='disease'),
    path('disease/<int:pk>/', diseases_views.detail_disease, name='detail_disease'),
    path('fruit_help/', diseases_views.fruit_help, name='fruit_help'),
    path('fruit_help/<int:disease_id>/', diseases_views.detail_disease_help, name='detail_disease_help'),
    path('fruit_help/<int:disease_id>/<int:element_id>/', diseases_views.detail_disease_help_element, name='detail_disease_help_element'),
    path('update/<int:element_id>/', views.update_fruit_detail, name='update_fruit_detail'),
    #using a form directly
    path('update/<int:element_id>/update/', views.update_fruit, name='update_fruit'),
    path('update/<int:element_id>/results/', views.update_fruit_results, name='update_fruit_results'),
    path('fruit/create/', views.FruitCreate.as_view(), name='fruit_create'),
    path('fruit/<int:pk>/update/', views.FruitUpdate.as_view(), name= 'fruit_update'),
    path('fruit/<int:pk>/delete/', views.FruitDelete.as_view(), name='fruit_delete'),
    path('disease/create', views.DiseaseCreate.as_view(), name='disease_create'),
    path('disease/<int:pk>/update/', views.DiseaseUpdate.as_view(), name= 'disease_update'),
    path('disease/<int:pk>/delete', views.DiseaseDelete.as_view(), name='disease_delete'),
    path('all_fruits_disease/', views.all_fruits_disease, name='all_fruit_disease'),
    path('all_fruits_disease/<int:disease_id>/', views.all_fruits_disease_detaill, name='all_fruit_disease_detail'),
    
] 

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  

app/fruit_therapy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diseases.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/diseases/models.py
from tkinter import CASCADE
from unittest.util import _MAX_LENGTH
from django.db import models, reset_queries
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Composition(models.Model):
    compound_name = models.CharField(max_length=30, blank=False)
    
    def __str__(self):
        return self.compound_name

class Customer(models.Model):
    name = models.CharField(max_length=50, blank=False)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Fruit(models.Model):
    #name = models.CharField(max_length=50, unique=True, blank=False, default='')
    name = models.CharField(max_length=50, unique=True, blank=False)
    scientific_name = models.CharField(max_length=50, null=True, blank=True)
    energy = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, default=0.00)

    def get_absolute_url(self):
        return reverse('detail_fruit', args=[str(self.id)])

    def __str__(self):
        return self.name

class Element(models.Model):
    name = models.CharField(max_length=50, unique=True, blank=False, default='')
    composition = models.ForeignKey(Composition, on_delete=models.CASCADE)
    um = models.CharField(max_length=4, null=True, blank=True, default='')

    def __str__(self):
        return f'{str(self.name)} {"("} {str(self.um)} {")"}'

class DiseaseF(models.Model):
    name = models.CharField(max_length=50, unique=True, blank=False, default='')
    descrip = models.TextField(null=True, blank=True, default='')

    def get_absolute_url(self):
        #return reverse('detail_disease', args=[str(self.id)])
        return reverse('fruit_therapy', args=[str(self.id)])
        
    def __str__(self):
        return self.name 


class Disease_Element(models.Model):
    disease = models.ForeignKey(DiseaseF, on_delete=models.CASCADE)
    element = models.ForeignKey(Element, on_delete=models.CASCADE)

    def __str__(self):
        return f'{str(self.disease)} {str(self.element)}'


class Fruit_Element(models.Model):
    fruit = models.ForeignKey(Fruit, on_delete=models.CASCADE)
    element = models.ForeignKey(Element, on_delete=models.CASCADE)
    amount = models.FloatField(null=True, blank=True, default=0.00)
    amountg = models.FloatField(null=True, blank=True, default=0.00)
    
    class Meta:
        ordering = ['-amount']

    def __str__(self):
        return f'{str(self.fruit)} {str(self.element)} {str(self.amount)}'


class Customer_Disease(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    disease = models.ForeignKey(DiseaseF, on_delete=models.CASCADE)

    def __str__(self):
        return f'{str(self.customer)} {str(self.disease)}'

app/diseases/views.py
from collections import UserList
from unicodedata import name
from urllib.request import urlretrieve
from django.http.response import JsonResponse
from rest_framework.parsers import JSONParser
from rest_framework import status
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from django.db.models import Q

from django.http import HttpResponse
from django.template import loader

from multiprocessing import context
from django.shortcuts import render, get_object_or_404
from diseases.serializers import DiseaseFSerializer, ElementSerializer, CompositionSerializer, Fruit_ElementSerializer, FruitSerializer
from rest_framework.decorators import api_view
from .models import Composition, Customer, Disease_Element, DiseaseF, Element, Fruit, Fruit_Element, User, Customer

from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
# Generic views
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Max, Aggregate
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, SetPasswordForm

from django.contrib.auth.backends import BaseBackend
from django.views import generic

from django.conf import settings
from django.contrib.auth.backends import BaseBackend
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User


# Create your views here.

def calculated_amoung_in_grams(unit, value):
    Fruit_Element.objects.all()
    fruit=Fruit_Element.objects.filter(element__um=unit, amountg=0)
    for f in fruit:
        f.amountg = f.amount*value
        f.save()
    Fruit_Element.objects.all()


#I'll delete this one
def dis_element(request):
    dis = DiseaseF.objects.all()
    if request.method == 'GET':
        diseases_serializer = DiseaseFSerializer(dis, many=True)
        list = []
        list.append(diseases_serializer.data)
        context = {'diseases': list}
        return render(request, 'dis_element.html', context)

# works
@api_view(['GET'])
def diseases_list(request):
    dis = DiseaseF.objects.all()

    if request.method == 'GET':
        diseases_serializer = DiseaseFSerializer(dis, many=True)
        return JsonResponse(diseases_serializer.data, safe=False)
        
# works
@api_view(['GET'])
def element_list(request):
    ele = Element.objects.all()

    if request.method == 'GET':
        element_serializer = ElementSerializer(ele, many=True)
        return JsonResponse(element_serializer.data, safe=False)

def detail(request, composition_id):
    composition = get_object_or_404(Composition, pk=composition_id)
    return render(request, 'diseases/detail.html', {'composition': composition})

def index_elements(request):
    element_list = Element.objects.order_by('name')
    context = {'element_list': element_list}
    return render(request, 'diseases/index_element.html', context)

def all_fruits_disease(request):
    #.order_by('name')
    dis_list = DiseaseF.objects.all().order_by('name')
    context = {'dis_list': dis_list}
    return render(request, 'diseases/all_fruits_disease.html', context)

def all_fruits_disease_detaill(request, disease_id):
    calculated_amoung_in_grams('g',1)
    calculated_amoung_in_grams('mg',0.001)
    calculated_amoung_in_grams('µg',0.000001)
    
    q=Fruit_Element.objects.values('fruit','fruit__name').annotate(maxamount=Max('amountg')).order_by('-maxamount')         
    list_element=q.filter(element__disease_element__disease=disease_id)
    name_disease = get_object_or_404(DiseaseF, pk=disease_id)
    context = {'list_element': list_element, 'name_disease': name_disease}
    return render(request, 'diseases/all_fruits_disease_detail.html', context)


def detail_element(request, element_id):
    element = get_object_or_404(Element, pk=element_id)
    #a = Disease_Element.get_deferred_fields(name)
    return render(request, 'diseases/detail_element.html', {'element': element})

def index_composition(request):
    composition_list = Composition.objects.all()
    context = {'composition_list': composition_list}
    return render(request, 'diseases/index_composition.html', context)

def index_disease(request):
    disease_list = DiseaseF.objects.all().order_by('name')
    context = {'disease_list': disease_list}
    success_url = reverse_lazy('fruit_therapy')
    return render(request, 'diseases/index_disease.html', context)
    

def detail_disease(request,pk):
    dis = get_object_or_404(DiseaseF, pk=pk)
    return render(request, 'diseases/detail_disease.html', {'disease': dis})

def index_fruit(request):
    fruit_list = Fruit.objects.all().order_by('name')
    context = {'fruit_list': fruit_list}
    return render(request, 'diseases/index_fruit.html', context)

def detail_fruit(request,pk):
    fruit = get_object_or_404(Fruit, pk=pk)
    return render(request, 'diseases/detail_fruit.html', {'fruit': fruit})

def fruit_therapy(request):  
    num_diseases=DiseaseF.objects.all().count()
    num_fruits=Fruit.objects.all().count()
    return render(request,'diseases/fruit_therapy.html', context={'num_diseases':num_diseases,'num_fruits':num_fruits})

def fruit_help(request):
    disease_list = DiseaseF.objects.all().order_by('name')
    context = {'disease_list': disease_list}
    return render(request, 'diseases/fruit_help.html', context)

def detail_disease_help(request,disease_id):
    disi=get_object_or_404(DiseaseF,pk=disease_id)
    return render(request, 'diseases/detail_disease_help.html', {'disease': disi})

def detail_disease_help_element(request,disease_id,element_id):
    elem = get_object_or_404(Element, pk=element_id)
    list_fruit = Fruit_Element.objects.filter(element=element_id)
    return render(request, 'diseases/detail_disease_help_element.html', {'list_fruit': list_fruit, 'elem': elem})

def update_fruit(request, element_id):
    element = get_object_or_404(Element, pk=element_id)
    try:
        
        selected_fruit_element = element.fruit_element_set.get(pk=request.POST['fruit_element'])
        amount = selected_fruit_element.amount
        
    except (KeyError, Fruit_Element.DoesNotExist):
        return render(request, 'diseases/update_fruit_detail.html', {
            'element': element,
            'error_message': "You didn't select an element yet."
        })
    else:
        selected_fruit_element.amount = amount
        selected_fruit_element.save()
        return HttpResponseRedirect(reverse('update_fruit_results', args=(element.id,)))
      
def update_fruit_detail(request, element_id):
    return HttpResponse("You're selecting amount for element: %s." % element_id)

def update_fruit_results(request, element_id):
    element = get_object_or_404(Element, pk=element_id)
    return render(request, 'diseases/update_fruit_results.html', {'element': element})

class FruitCreate(CreateView):
    model = Fruit
    fields = '__all__'

class FruitUpdate(UpdateView):
    model = Fruit
    fields = ['name','scientific_name','water_percent']

class FruitDelete(DeleteView):
    model = Fruit
    success_url = reverse_lazy('fruit')

class DiseaseCreate(CreateView):
    model = DiseaseF
    fields = '__all__'
    success_url = reverse_lazy('disease')

class DiseaseUpdate(UpdateView):
    model = DiseaseF
    fields = ['name','descrip']
    success_url = reverse_lazy('disease')

class DiseaseDelete(DeleteView):
    model = DiseaseF
    success_url = reverse_lazy('disease')

class SettingsBackend(BaseBackend):

    def authenticate(self, request, username=None, password=None):
        login_valid = (settings.ADMIN_LOGIN == username)
        pwd_valid = check_password(password, settings.ADMIN_PASSWORD)
        if login_valid and pwd_valid:
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                user = User(username=username)
                user.is_staff = True
                user.is_superuser = True
                user.save()
            return user
        return None

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None

app/diseases/templates/diseases/all_fruits_disease.html
{% if dis_list %}
<ul>
    {% for disease in dis_list %}
    <li><a href="{% url 'all_fruit_disease_detail' disease.id %}">{{ disease.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No Diseases are available.</p>
{% endif %}

app/diseases/templates/diseases/all_fruits_disease_detail.html
<h1>List of Fruits that helps: {{ name_disease }} .Order by Greater Amount of Element in the Fruits</h1>
<ul>
    {% for fruit in list_element %}
    <li>{{ fruit.fruit__name }}</li>
    {% endfor %}
</ul>



<p>Be aware mostly fruits can contain: <em>A High Amount of SUGAR and SODIUM</em></p>

app/diseases/templates/diseases/detail.html
<h1>{{ composition.compound_name }}</h1>
<ul>
    {% for element in composition.element_set.all %}
    <li>{{ element.name }}</li>
    {% endfor %}
</ul>

app/diseases/templates/diseases/detail_disease_help.html
<h1>{{ disease.name }}</h1>
<ul>
    {% for disease_element in disease.disease_element_set.all %}
    <h2>{{disease_element.element}}</h2>
    <li><a href="{% url 'detail_disease_help_element' disease_element.disease.id disease_element.element.id %}">
            Order_By_Amount's_Fruits_That_Help</a></li>
    {% endfor %}
</ul>

app/diseases/templates/diseases/detail_disease_help_element.html
{% if list_fruit %}
<ul>
    <h1>The Corresponding Amount For a Portion of 100 g Fruit's</h1>
    <h2>Element: {{ elem.name }}. Unit of Measurement({{elem.um}})</h2>
    {% for fruit in list_fruit %}
    <li>{{fruit.fruit}}: {{fruit.amount}}</li>
    {% endfor %}
</ul>
{% else %}
<p>No fruits are available.</p>
{% endif %}

app/diseases/templates/diseases/diseasef_confirm_delete.html
{% block content %}

<h1>Delete Disease</h1>

<p>Are you sure you want to delete the disease: {{ diseasef.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

app/diseases/templates/diseases/fruit_confirm_delete.html
{% block content %}

<h1>Delete Fruit</h1>

<p>Are you sure you want to delete the fruit: {{ fruit.name }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

app/diseases/templates/diseases/fruit_therapy.html
{% block content %}

<head>
    <li><a href="{% url 'composition' %}">All Compositions</a></li>
    <li><a href="{% url 'element' %}">All Elements</a></li>
    <li><a href="{% url 'fruit' %}">All Fruits</a></li>
    <li><a href="{% url 'disease' %}">All Diseases</a></li>
    <li><a href="{% url 'fruit_help' %}">Diseases helped by fruits by Elements</a></li>
    <li><a href="{% url 'all_fruit_disease' %}">Best fruits for a Diseases</a></li>

</head>

<h1>Fruit_Therapy Home</h1>

<p>Welcome to <em>Fruit_Therapy</em>, A Django API to make the consume of the Fruits a way to improves Diseases</p>

<h2>Dynamic content</h2>

<p>The Fruit_Therapy has the following record counts:</p>
<ul>
    <li><strong>Diseases:</strong> {{ num_diseases }}</li>
    <li><strong>Fruits:</strong> {{ num_fruits }}</li>
</ul>

{% if user.is_authenticated %}
<li>User: {{ user.get_username }}</li>
<li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
{% else %}
<li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
{% endif %}
</ul>
{% endblock %}

app/diseases/templates/diseases/index.html
{% if disease_list %}
<ul>
    {% for diseasef in disease_list %}
    <li><a href="{% url 'detail' diseasef.id %}">{{ diseasef.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No diseases are available.</p>
{% endif %}

app/diseases/templates/diseases/index_composition.html
{% if composition_list %}
<ul>
    {% for composition in composition_list %}
    <li><a href="{% url 'detail' composition.id %}">{{ composition.compound_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No diseases are available.</p>
{% endif %}

app/diseases/templates/diseases/index_disease.html
{% block content %}
{% if disease_list %}
<ul>
    {% for disease in disease_list %}
    <li><a href="{% url 'detail_disease' disease.id %}">{{ disease.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No diseases are available.</p>
{% endif %}

<li><a href="{% url 'disease_create'%}?next={{request.path}}">Create</a></li>
{% endblock %}

app/diseases/templates/diseases/index_fruit.html
{% if fruit_list %}
<ul>
    {% for fruit in fruit_list %}
    <li><a href="{% url 'detail_fruit' fruit.id %}">{{ fruit.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No fruits are available.</p>
{% endif %}

app/diseases/templates/diseases/update_fruit_detail.html
<form action="{% url 'update_fruit' element.id %}" method="post">

    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ element.name }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for fruit_element in element.fruit_element_set.all %}
        <input type="radio" name="fruit_element" id="fruit_element{{ forloop.counter }}" value="{{ fruit_element.id }}">
        <label for="fruit_element{{ forloop.counter }}">{{fruit_element.fruit}}</label>
        <input id="fruit_element" type="text" name="amount" value="{{ fruit_element.amount }}"><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Update">
</form>

app/diseases/templates/diseases/update_fruit_results.html
<h1>{{ element.name }}</h1>

<ul>
    {% for fruit_element in element.fruit_element_set.all %}
    <li>{{ fruit_element.amount }} -- {{ fruit_element.fruit }}</li>
    {% endfor %}
</ul>